version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - db_connection

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db_connection

  ui:
    build:
      context: ui
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - api_connection

  api:
    build:
      context: api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - db_connection
      - api_connection

networks:
  db_connection:
    driver: bridge
  api_connection:
    driver: bridge
