version: '3.4'

services:
  dbtermprojectfrontend:
    image: dbtermprojectfrontend
    build:
      context: ui
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  dbtermprojectbackend:
    image: dbtermprojectbackend
    build:
      context: api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000

